### ISSUE TITLE
Copy files

### ISSUE THREAD

**Issue by glederer007** [DeanCording/node-red-contrib-fs-ops#6]
Hello,

I have a question that may sound very stupid, if that is the case, I apologize for it. 

I would like to copy a specific file from one directory to another on a raspberry. If I use fs-ops-move it will move it not copy it. But I need to keep the original file. Are you planning to add something like  fs-ops-copy?

Regards,

Gabor

**Comment by DeanCording** [comment]
Actually, that's a very good question.  I have no idea why I didn't implement fs-ops-copy originally.  I'll do it shortly.

Thanks,

Dean

**Comment by glederer007** [comment]
Thanks a lot, that would be great!

**Comment by DeanCording** [comment]
Ah,I understand why there was no fs-ops-copy now - it wasn't supported in Node 7 and only got added in Node 8.5.

**Comment by glederer007** [comment]
I would like to use it to interface to a raspbx based open source pbx (http://www.raspberry-asterisk.org/). In this package - using a USB 3G stick - it is possible to initiate outgoing phone calls by copying certain command files to specific directories. After the outgoing call is completed, the copied file is deleted by raspbx. So if I move the file instead of copy it, I would have to generate it every time an outgoing call is initiated. This is why I need copy instead of move. But of course it is up to you to decide if it is worth spending your time in implementing the "copy node".

**Comment by DeanCording** [comment]
File Copy has been implemented with options to link instead of copy, and prevent overwrites.

**Comment by glederer007** [comment]
Hello,

Great, thanks, I will try it this weekend.

Regards,

Gabor

**Comment by glederer007** [comment]
Sorry, one more thing. Will you update the library that can be downloaded from nodered.org?

**Comment by DeanCording** [comment]
Already done.  `npm update` should bring it down.

**Comment by glederer007** [comment]
Thanks!
